### ISSUE TITLE
Feature Request: More syntax languages

### ISSUE THREAD

**Issue by endigma** [heyman/heynote#10]
Notably missing:

- Golang
- Ruby
- Shell
- Typescript
- YAML
- TOML
- HCL
- R
- Ini
- Properties

**Comment by endigma** [comment]
From #11 

- Elixir
- Erlang

**Comment by heyman** [comment]
Heynote uses [Lezer](https://lezer.codemirror.net/) for its syntax highlighting, and if a Lezer parser exist for a language it's fairly trivial to add it to Heynote. 

I just found [this repo](https://github.com/codemirror/legacy-modes) which seems to have support for 
some of those languages, so it might be easy to add. I will look into it!

**Comment by endigma** [comment]
From #19 

- Vue
- Rails (Ruby)

**Comment by endigma** [comment]
@heyman Could probably pin this to avoid dupe spam

**Comment by endigma** [comment]
> Heynote uses [Lezer](https://lezer.codemirror.net/) for its syntax highlighting, and if a Lezer parser exist for a language it's fairly trivial to add it to Heynote.
> 
> I just found [this repo](https://github.com/codemirror/legacy-modes) which seems to have support for some of those languages, so it might be easy to add. I will look into it!

https://github.com/orgs/codemirror/repositories?language=&q=lang-&sort=&type=all

**Comment by cursive-ide** [comment]
Clojure/EDN support would also be nice, and [this](https://github.com/nextjournal/lezer-clojure) is linked from Lezer itself.

**Comment by CoenraadS** [comment]
C# (csharp)

**Comment by espenja** [comment]
From #64 
- TypeScript

**Comment by heyman** [comment]
Most of the requested Languages have now been added. I've released a new beta version (you can update to it by turning on Beta versions in Heynote's settings).

**Comment by eizedev** [comment]
- PowerShell

**Comment by windymelt** [comment]
Scala support would be nice, thank you!

**Comment by jonedmiston** [comment]
Liquid would be helpful for us.

**Comment by aiiv** [comment]
dart

**Comment by TheMadLeprechaun** [comment]
AsciiDoc would be great.

**Comment by porridgewithraisins** [comment]
Support for git diffs (in vscode language list it is `Diff`) would be great.

**Comment by richieadler** [comment]
We have Markdown, AsciiDoc was requested... is only fair that we have [reStructuredText](https://docutils.sourceforge.io/rst.html) also.

**Comment by heyman** [comment]
> PowerShell

> Support for git diffs (in vscode language list it is Diff) would be great.

PowerShell and Diff support fixed in #191

**Comment by MystPi** [comment]
I would love support for [Gleam](https://gleam.run)!

**Comment by dljsjr** [comment]
Would love to see Lua support added :)

**Comment by benkates** [comment]
+1 for R, thanks!

**Comment by Akselmo** [comment]
I'd like to see [Odin](https://odin-lang.org/) language :)

**Comment by renyuneyun** [comment]
Would be great to see support for RDF-related syntaxes. In particular (in order of personal preference):

- Turtle
  - Then full N3 (Notation 3)
- SPARQL
- JSON-LD (well, it's almost just JSON, but with some special keywords; syntax highlight is for types of data, the special keywords, and then prefixes if possible)
- RDF/XML (well, it's almost just XML)

**Comment by jc00ke** [comment]
I'd love to help out with getting Elixir added, but my initial stab at it has proven unfruitful. There's a [lezer-elixir](https://www.npmjs.com/package/lezer-elixir) and it's used in [codemirror-lang-elixir](https://www.npmjs.com/package/codemirror-lang-elixir) but I'm not quite sure how to wire it up. I first attempted to wire it up the same way as Erlang, and then tried Markdown, then like `javascriptLanguage`, no luck with any. 

This is the error I keep seeing when I select Elixir from the language list:

```
TypeError: Cannot read properties of null (reading 'from')
    at enter (block.js:39:69)
    at _Tree.iterate (chunk-6BKTIZNU.js?v=2f35efac:322:75)
    at getBlocksFromSyntaxTree (block.js:33:14)
    at getBlocks (block.js:143:16)
    at _StateField.update [as updateF] (block.js:157:20)
    at Object.update (chunk-UG2KWNZJ.js?v=2f35efac:1671:26)
    at _EditorState.computeSlot (chunk-UG2KWNZJ.js?v=2f35efac:2311:85)
    at ensureAddr (chunk-UG2KWNZJ.js?v=2f35efac:1892:23)
    at new _EditorState (chunk-UG2KWNZJ.js?v=2f35efac:2250:7)
    at _EditorState.applyTransaction (chunk-UG2KWNZJ.js?v=2f35efac:2311:5)
```

I can't track down why that `langNode` would be `null`. 🤷‍♂️ 

I'm working off of ff88091e28ce2fe1c7615adc1544301b7ec8d8d8.

Thanks for your help and I'm looking forward to using HeyNote! Happy to move this to a separate issue if you want, LMK.

**Comment by elkarouh** [comment]
Add support for Nim and Ada
