### ISSUE TITLE
Bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by AmintaCCCP** [heyman/heynote#150]
**Describe the bug**

When I open heynote.app, the following error message pops up:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `settings/fontFamily` must be string; `settings/fontSize` must be integer
at DD._validate (/Applications/Heynote.app/Contents/Resources/app.asar/dist-electron/main/index.js:16:39004)
at new J (/Applications/Heynote.app/Contents/Resources/app.asar/dist-electron/main/index.js:16:35709)
at new DD (/Applications/Heynote.app/Contents/Resources/app.asar/dist-electron/main/index.js:16:41741)
at Module.<anonymous> (/Applications/Heynote.app/Contents/Resources/app.asar/dist-electron/main/index.js:16:43297)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at l._load (node:electron/js2c/asar_bundle:2:13642)
at node:electron/js2c/browser_init:2:120247
```

**Screenshots**
<img width="556" alt="image" src="https://github.com/heyman/heynote/assets/74942183/a7b95b80-07ff-4979-8ea3-40f09f8c1dc2">

**Desktop (please complete the following information):**
 - OS: [14.3 Beta (23D5051b) | M1 Pro Max]
 - Version [e.g. 1.6.0-beta4]

**Additional context**
I have tried to download and use the following two versions, but they all caused errors.
- Heynote_1.6.0-beta.4_arm64.dmg
- Heynote_1.6.0-beta.4_universal.dmg

**Comment by heyman** [comment]
Thanks for the report! I've fixed it and released a new beta version.
